spring:
  profiles:
    active: dev

  banner:
    charset: utf-8

  datasource:
    url: jdbc:mysql://localhost:3306/b2c?serverTimezone=UTC
    password: root
    username: root
    druid:
      initial-size : 5
      min-idle : 10
      max-active : 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid


mybatis:
  mapper-locations: classpath:mapper/*.xml ,classpath*:com/**/mapper/*.xml

  config-location:  classpath:mybatis-config.xml

logging:
  level:
    root: info
    com.max: debug

server:
  port: 8088
  servlet:
    context-path:


