spring:
  datasource:
    url: jdbc:mysql://localhost:3306/b2c?serverTimezone=UTC
    password: root
    username: root
    druid:
      initial-size : 5
      min-idle : 10
      max-active : 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

mybatis:
  mapper-locations: classpath:dao/*.xml ,classpath*:com/**/dao/*.xml